version: '3.9'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql:5.7
        ports:
      # <Port exposed> : < MySQL Port running inside container>
          - '9906:3306'
        restart: always 
        environment:
            - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=MYSQL_DATABASE
            - MYSQL_USER=MYSQL_USER
            - MYSQL_PASSWORD=MYSQL_PASSWORD
    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
      # <Port exposed> : < MySQL Port running inside container>
          - '8080:80'
      depends_on: 
          - db
      environment:
            - PMA_HOST=db
